services:
  sane:
    build:
      context: sane
    expose:
      - "9410"
    environment:
      - PORT=9410
    ports:
      - "9410:9410"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9410" ]
