services:
  sane:
    build:
      context: sane
    expose:
      - "9410"
    environment:
      - PORT=9410
    ports:
      - "9410:9410"
    healthcheck:
      test:
        [
          "CMD",
          "/usr/bin/curl",
          "-s",
          "--fail",
          "http://localhost:9410/health-check"
        ]
      interval: 10s
      timeout: 10s
      retries: 3
